site_name: RADx Metadata Specification
site_url: https://example.com/

nav:
    - Home: index.md
    - Preliminaries: preliminaries.md
    - Language Codes: language-codes.md
    - Specification: specification.md
    - Creating Metadata: creating-metadata.md
    - About: about.md

theme: readthedocs