site_name: RADx Metadata Specification
site_url: https://radx.github.io/radx-metadata-specification-docs/

nav:
    - Home: index.md
    - Preliminaries: preliminaries.md
    - Specification: specification.md
    - Creating Metadata: creating-metadata.md
    - Language Codes: language-codes.md
    - About: about.md
    - RADx DCC-Specific Mappings:
        - RADx-rad: radx-rad-mapping.md

theme: readthedocs
